/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model
import (
	"time"
)
// Group struct for Group
type Group struct {
	Id         int64      `json:"id"`
	Uuid       string     `json:"uuid"`
	Name       string     `json:"name"`
	Created    time.Time  `json:"created,omitempty"`
	Updated    time.Time  `json:"updated,omitempty"`
	Visibility Visibility `json:"visibility,omitempty"`
}
