/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model
import (
	"time"
)
// Membership struct for Membership
type Membership struct {
	Id         int64      `json:"id,omitempty"`
	Uuid       string     `json:"uuid"`
	Created    time.Time  `json:"created"`
	User       User       `json:"user"`
	Group      Group      `json:"group"`
	Permission Permission `json:"permission"`
}
