/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model
// NewGroup struct for NewGroup
type NewGroup struct {
	Name       string     `json:"name"`
	Visibility Visibility `json:"visibility"`
}
