/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model
// NewUser struct for NewUser
type NewUser struct {
	Name string `json:"name,omitempty"`
	Email string `json:"email"`
	Password string `json:"password"`
}
