/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model
import (
	"time"
)
// Password struct for Password
type Password struct {
	Id       int64     `json:"id,omitempty"`
	Uuid     string    `json:"uuid,omitempty"`
	User     User      `json:"user,omitempty"`
	Password string    `json:"password"`
	Created  time.Time `json:"created,omitempty"`
}
