apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  type: ClusterIP
  selector:
    app: image-service
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: http
